### ISSUE TITLE
Android memo research spike (PIR)

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash-android-wallet-poc#13]
Understand how to grab memos and display memos for transactions in the wallet. 

Currently, lightwalletd can also get a full transaction with `gettransaction`. We should figure out when we should do this, and how to minimize the security, privacy, and performance implications. 

I.e. we can do this responsively as we detect that a transaction belongs to the wallet, or do it periodically after a batch of blocks have been scanned. 

Outcomes
- [ ] Design for full transaction retrieval for SDKs
- [ ] Security Assessment of design
- [ ] Tickets for implementation in SDK
- [ ] Tickets for implementation in zECC
- [ ] Enumerate any dependencies on LRZ/Core and discuss in research spike review

Timebox: 3 hours

**Comment by lindanlee** [comment]
Brad and Kevin have the context, and will update this ticket after a conversation.

**Comment by gmale** [comment]
Just discussed this in backlog grooming. @defuse mentioned potentially doing some research in this area but until then, just asking for what we need.

This ticket basically addresses Private retrieval for memos.

**Comment by defuse** [comment]
Yeah for now the best we can do is ask lightwalletd directly for what we need, and try to make it clear to users that when they take such actions their privacy is in the hands of the lightwalletd server they connect to. (This will be an interesting exercise in designing UX that communicates risk to users without being cumbersome! @geffenz @lindanlee).

ZIP 307 says:

> The light client SHOULD obscure the exact transactions of interest by downloading numerous uninteresting transactions as well, and SHOULD download all transactions in any block from which a single full transaction is fetched (interesting or otherwise). It MUST convey to the user that fetching full transactions will reduce their privacy.

I disagree with the "SHOULD"s because without careful reasoning about the privacy properties of the approach, it will just give everyone a false sense of security. The "MUST" is crucial though!

It may be possible to use PIR scheme here, depending on how bandwidth efficient they are. Or we might end up having to design an ad-hoc protocol where we request more than we need to create an anonymity set to hide in, perhaps using fresh Tor circuits to prevent intersection attacks, chaff traffic to kill traffic analysis side-channels, etc. 

I will look into the latest research and write up some suggestions!

**Comment by gmale** [comment]
Memos are live and work to do it more privately is tracked elsewhere
