### ISSUE TITLE
Internal-Security-Finding #1: Protect screens displaying secret keys from screenshots / app preview list

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-android-wallet-poc#3]
The contents of the app's window can be protected by setting [WindowManager.LayoutParams.FLAG_SECURE](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE). It will help ensure people don't accidentally take a screenshot of their secret key, or it being shown in the app preview (increasing the chances it gets leaked to somewhere insecure).

**Comment by lindanlee** [comment]
Great, this is something we should add along with backup and recovery. 

For now, we don't have backup and restore implemented, since this reference wallet mainly to help partners integrate shielded addresses, and they struggle with detecting shielded transactions and spending shielded notes. 

We suspected that they wouldn't need help with generating keys and backing them up, since they already have infrastructure for that. This is true for transparent addresses but we're not sure about shielded addresses. Is there something fundamentally different about zaddresses that can't be worked with existing standards, @str4d ?

**Comment by defuse** [comment]
Ah, this isn't really even an issue then. I assumed backup/restore was in there somewhere without actually seeing any code for it! If we implement backup/restore then it's worth doing in case someone is following our example really closely, but existing third-parties should already be managing this.

**Comment by lindanlee** [comment]
> Ah, this isn't really even an issue then. I assumed backup/restore was in there somewhere without actually seeing any code for it! If we implement backup/restore then it's worth doing in case someone is following our example really closely, but existing third-parties should already be managing this.

Yep, this is a non-issue for now, as far as I am concerned. 

The fact that our app is not an end product but a resource to partners is the key difference. Thanks for being on the lookout! We should keep that in mind if we were to ever consider deploying our own wallet (I think this is dropped for 2019, but not forever, AFAIK).

**Comment by gmale** [comment]
Closing per discussion. This is a great feature for a full wallet but out of scope for this wallet.
